server:
  port: 8080

spring:
  application:
    name: kafkamessaging

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

logging:
  level:
    root: INFO
    com.example.kafkamessaging: DEBUG
